[package]
name = "fe_scratch"
description = "Scratch project for trying out stuff with a CI"
license = "MPL-2.0"
rust-version = "1.64"
version = "0.0.1"
edition = "2021"

[dependencies]
hyper = { version = "0.14", features = ["client", "http1", "http2"] }
