name: CI
on: [push, pull_request]

jobs:
  deny:
    name: Cargo deny
    strategy:
      matrix:
        os:
          #- macOS-latest
          #- ubuntu-20.04
          - windows-2022
        toolchain:
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      # Install is very slow (5 min on Ubuntu, 10 minutes on Mac and Windows)
      - run: cargo install cargo-deny
      - run: cargo deny check
  test:
    name: Cargo test
    strategy:
      matrix:
        os:
          #- macOS-latest
          #- ubuntu-20.04
          - windows-2022
        toolchain:
          - 1.64
          #- beta
          #- nightly
          #- stable
        #exclude:
          #- os: macOS-latest
          #  toolchain: beta
          #- os: macOS-latest
          #  toolchain: nightly
          #- os: windows-2022
          #  toolchain: beta
          #- os: windows-2022
          #  toolchain: nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          #components: "clippy"
          toolchain: ${{ matrix.toolchain }}
      #- run: cargo clippy
      - run: docker version
      - run: docker image ls
      - run: docker container ls
      #- run: Get-Service
      - run: Stop-Service docker
      #- run: gwmi -Query "select * from win32_service where pathname like '%$docker%'"
      - run: Get-CimInstance Win32_Service -Filter 'Name = "docker"' | Select-Object *
      - run: |
          Set-Content -Path "C:\ProgramData\Docker\config\daemon.json" -Value "{`"hosts`": [`"tcp://0.0.0.0:2375`"]}"
      - run: type C:\ProgramData\Docker\config\daemon.json
      - run: C:\Windows\system32\dockerd.exe --help
      - run: Start-Service docker
      - run: Get-CimInstance Win32_Service -Filter 'Name = "docker"' | Select-Object *
      #- run: cargo test
      - run: cargo b --examples
      - run: cargo run --example barey